In [85]:
import pandas as pd
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from imblearn.combine import SMOTEENN

In [86]:
df=pd.read_csv('telcoo.csv')

In [87]:
df.head()

,Unnamed: 0,SeniorCitizen,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,0,29.85,29.85,0,True,False,False,True,True,...,False,False,True,False,True,False,False,False,False,False
1,1,0,56.95,1889.50,0,False,True,True,False,True,...,False,False,False,True,False,False,True,False,False,False
2,2,0,53.85,108.15,1,False,True,True,False,True,...,False,False,False,True,True,False,False,False,False,False
3,3,0,42.30,1840.75,0,False,True,True,False,True,...,True,False,False,False,False,False,False,True,False,False
4,4,0,70.70,151.65,1,True,False,True,False,True,...,False,False,True,False,True,False,False,False,False,False

In [88]:
df=df.drop('Unnamed: 0',axis=1)

In [89]:
df.head()

,SeniorCitizen,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,29.85,29.85,0,True,False,False,True,True,False,...,False,False,True,False,True,False,False,False,False,False
1,0,56.95,1889.50,0,False,True,True,False,True,False,...,False,False,False,True,False,False,True,False,False,False
2,0,53.85,108.15,1,False,True,True,False,True,False,...,False,False,False,True,True,False,False,False,False,False
3,0,42.30,1840.75,0,False,True,True,False,True,False,...,True,False,False,False,False,False,False,True,False,False
4,0,70.70,151.65,1,True,False,True,False,True,False,...,False,False,True,False,True,False,False,False,False,False

In [90]:
x=df.drop('Churn',axis=1)
x

,SeniorCitizen,MonthlyCharges,TotalCharges,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,PhoneService_No,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,29.85,29.85,True,False,False,True,True,False,True,...,False,False,True,False,True,False,False,False,False,False
1,0,56.95,1889.50,False,True,True,False,True,False,False,...,False,False,False,True,False,False,True,False,False,False
2,0,53.85,108.15,False,True,True,False,True,False,False,...,False,False,False,True,True,False,False,False,False,False
3,0,42.30,1840.75,False,True,True,False,True,False,True,...,True,False,False,False,False,False,False,True,False,False
4,0,70.70,151.65,True,False,True,False,True,False,False,...,False,False,True,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,0,84.80,1990.50,False,True,False,True,False,True,False,...,False,False,False,True,False,True,False,False,False,False
7028,0,103.20,7362.90,True,False,False,True,False,True,False,...,False,True,False,False,False,False,False,False,False,True
7029,0,29.60,346.45,True,False,False,True,False,True,True,...,False,False,True,False,True,False,False,False,False,False
7030,1,74.40,306.60,False,True,False,True,True,False,False,...,False,False,False,True,True,False,False,False,False,False
7031,0,105.65,6844.50,False,True,True,False,True,False,False,...,True,False,False,False,False,False,False,False,False,True

In [91]:
y=df['Churn']
y

0       0
1       0
2       1
3       0
4       1
       ..
7027    0
7028    0
7029    0
7030    1
7031    0
Name: Churn, Length: 7032, dtype: int64

In [92]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [93]:
#decision tree classifier

In [94]:
model_dt=DecisionTreeClassifier(criterion = "gini" , random_state=100,max_depth=6,min_samples_leaf=8)

In [95]:
model_dt.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [96]:
y_pred=model_dt.predict(x_test)
y_pred

array([0, 1, 0, ..., 0, 1, 0], shape=(1407,))

In [97]:
model_dt.score(x_test,y_test)

0.7938877043354655

In [98]:
print(classification_report(y_test,y_pred,labels=[0,1]))

              precision    recall  f1-score   support

           0       0.84      0.89      0.87      1051
           1       0.61      0.51      0.55       356

    accuracy                           0.79      1407
   macro avg       0.73      0.70      0.71      1407
weighted avg       0.78      0.79      0.79      1407

In [99]:
#the accuracy is bad because the data is imbalanced ,hence we use smoteenn

In [100]:
sm = SMOTEENN()
x_resample,y_resample = sm.fit_resample(x,y)

In [101]:
xr_train,xr_test,yr_train,yr_test=train_test_split(x_resample,y_resample,test_size=0.2)

In [102]:
model_dt_smote=DecisionTreeClassifier(criterion='gini',max_depth=6,random_state=100,min_samples_leaf=8)

In [103]:
model_dt_smote.fit(xr_train,yr_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [104]:
yr_pred=model_dt_smote.predict(xr_test)
yr_pred

array([1, 1, 1, ..., 0, 0, 0], shape=(1178,))

In [105]:
model_dt_smote.score(xr_test,yr_test)

0.9219015280135824

In [106]:
print(classification_report(yr_test,yr_pred,labels=[0,1]))

              precision    recall  f1-score   support

           0       0.92      0.91      0.91       539
           1       0.93      0.93      0.93       639

    accuracy                           0.92      1178
   macro avg       0.92      0.92      0.92      1178
weighted avg       0.92      0.92      0.92      1178

In [108]:
from sklearn.ensemble import RandomForestClassifier

In [117]:
model_rf_smote=RandomForestClassifier(n_estimators=100,criterion='gini',random_state=100,max_depth=6,min_samples_leaf=8)

In [118]:
model_rf_smote.fit(xr_train,yr_train)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [119]:
yr_pred=model_rf_smote.predict(xr_test)

In [120]:
model_rf_smote.score(x_test,y_test)

0.7555081734186212

In [121]:
print(classification_report(yr_test,yr_pred,labels=[0,1]))

              precision    recall  f1-score   support

           0       0.94      0.90      0.92       539
           1       0.92      0.95      0.93       639

    accuracy                           0.93      1178
   macro avg       0.93      0.93      0.93      1178
weighted avg       0.93      0.93      0.93      1178

In [122]:
print(confusion_matrix(yr_test,yr_pred))

[[487  52]
 [ 33 606]]

In [123]:
import pickle

In [124]:
filename='churn.model'

In [125]:
pickle.dump(model_rf_smote,open(filename,'wb'))

In [127]:
load_model=pickle.load(open(filename,'rb'))

In [128]:
load_model.score(xr_test,yr_test)

0.9278438030560272